### PR TITLE
Pin sslyze to v2.x

### PR DESCRIPTION
**Pull request by cablej**
Several issues have been reported due to breaking changes in sslyze's latest versions (#210, #209). This PR takes the [same strategy of domain-scan](https://github.com/18F/domain-scan/commit/0e437dc84607e29b177007ec774695c60d27f79c) in pinning sslyze to under v3 in order to retain functionality.

### CODE REVIEW

**Comment by jsf9k** [comment]
Thanks for taking care of this @cablej!  I'll take a look at the failing build tonight or tomorrow morning.

**Comment by mcdonnnj** [comment]
Thanks for your contribution @cablej ! I believe the error in the Travis build can be resolved by changing https://github.com/cisagov/pshtt/blob/43dcd5874c1ea04059e40a824fd1ec1bc1c74ed9/.travis.yml#L23
to `pip install --upgrade flake8 pytest-cov pytest coveralls`. It appears that there's an older version of `pytest` on the Travis instance that is incompatible with newer versions of `pytest-cov`, and that breaks the `pytest` run.

**Comment by jsf9k** [comment]
I made @mcdonnnj's suggested change, but now there is another problem where it can't find a suitable wheel for [the nassl package](https://pypi.org/project/nassl/).  I will revisit this in the morning.

**Review by jsf9k — APPROVED** [review]
Thanks again to @cablej for taking care of this.

**Comment by jsf9k** [comment]
I'll temporarily turn off the TravisCI Branch check in order to merge this once there are enough reviews in place.

**Review by h-m-f-t — APPROVED** [review]
LGTM!

**Review by mcdonnnj — APPROVED** [review]
Thanks again for the work @cablej 👍

**Pull request merged**
