### PR TITLE
Added Missing SAN check for cert parsing

### PR DESCRIPTION
**Pull request by amirian28**
Checks and flags a website if it has a missing SAN according to sslyze. You can verify this on arunachaltp.nic.in.

### CODE REVIEW

**Comment by amirian28** [comment]
@eric-zeng, @estark37 could you LGTM this? Thanks!

**Comment by konklone** [comment]
To me, this feels more like part of the category of "bad hostname", which we already have. That category is meant to be `True` when the part of the validation that fails is hostname validation, which this is a case of.

Detecting it is definitely valuable, and what's in `master` currently doesn't mark Bad Hostname as True. Could you update this PR to set the `https_bad_hostname` flag as False instead of creating a new flag?

**Comment by amirian28** [comment]
Ok, I see where you're coming from --- I had a similar thought to myself earlier today but figured I'd start by separating them out, even though one is kinda a subset of the other. 

So, to clarify, in the sslyze checking in https_check, you'd prefer to see https_bad_hostname set to True  instead of https_missing_san? I'm just a little confused because in your previous comment, you ask to set it to False, hence the clarification.

If that's the case, I can go ahead and make that change and remove the https_missing_san!

**Comment by konklone** [comment]
Sorry, yes, I meant True. :)

**Comment by amirian28** [comment]
Ok, should be fixed now.

**Comment by estark37** [comment]
LGTM!

**Comment by estark37** [comment]
LGTM!

**Comment by konklone** [comment]
Thank you, @amirian28!

**Pull request merged**
