### PR TITLE
Default to building universal wheel

### PR DESCRIPTION
**Pull request by IanLee1521**
Because the project is pure Python and 2/3 compatible,
we can build a single wheel out of the package using:

`$ python setup.py bdist_wheel`

Ref: https://packaging.python.org/tutorials/distributing-packages/#universal-wheels

### CODE REVIEW

**Comment by konklone** [comment]
Are you sure? I think `sslyze` has C extensions.

**Comment by IanLee1521** [comment]
It does, but the "universal-ness" of a package depends only on itself, not on its dependencies.

**Comment by konklone** [comment]
OK, that seems reasonable (and yeah, rereading the docs, I understand better now).

The examples in the docs say `universal = 1`, but you used `universal = true`. Will it work either way?

**Comment by IanLee1521** [comment]
Yes, I've used true in other places (and think it's clearer / better documenting). 

I also tested building the wheel locally.

**Comment by konklone** [comment]
Cool - looks good to me, but deferring to @h-m-f-t for merges of PyPi-related stuff, since I don't have any role in the packaging process (and haven't ever managed a PyPi package).

**Pull request merged**
