### PR TITLE
Couple of minor corrections to README

### PR DESCRIPTION
**Pull request by felddy**
Fixed a link and a typo.

### CODE REVIEW

**Comment by jsf9k** [comment]
Good eye, @felddy!  I will fix the broken build and then approve.

**Review by jsf9k — APPROVED** [review]
I had to add some fixes due to old TravisCI code.  Now approved.

I didn't debug exactly why the Python 3.6 build on the TravisCI outdated Docker build failed.  I just moved to 3.7 on VM Xenial.

**Comment by jsf9k** [comment]
@felddy you can go ahead and merge.  Or I can, if you prefer.

**Comment by IanLee1521** [comment]
@jsf9k -- there were some issues / transitions that had to happen in Travis (see https://docs.travis-ci.com/user/languages/python/#specifying-python-versions and https://github.com/travis-ci/travis-ci/issues/7085) which might have been what was going on... Just an fyi in case you weren't aware.

**Pull request merged**
