### PR TITLE
Some tweaks to the README

### PR DESCRIPTION
**Pull request by konklone**
This adds whitespace in some places, specifies that M-15-13 is about public stuff, and references me by name instead of by handle.

### CODE REVIEW

**Comment by konklone** [comment]
To avoid a merge conflict, I'm going to add a couple README-related changes to this PR. Don't merge yet.

**Comment by konklone** [comment]
I added https://github.com/dhs-ncats/pshtt/pull/80/commits/433663ed150717eabf250d875639a6d748137332, which documents the `--suffix-cache` flag in the README, and adds a debug logging statement when downloading the PSL (not just when caching it).

**Comment by konklone** [comment]
(This is ready for review and merge now.)

**Comment by h-m-f-t** [comment]
LGTM, thank you for making these changes 💯

**Pull request merged**
