### PR TITLE
Distinguish between connection errors and other exceptions

### PR DESCRIPTION
**Pull request by konklone**
This makes a (very ordinary) failure to connect an endpoint sound less threatening and like a real error, and leaves the "unexpected" error to a generic requests error that isn't a failure to connect.

### CODE REVIEW

**Comment by h-m-f-t** [comment]
👍

**Comment by konklone** [comment]
Did you mean to merge?

**Comment by konklone** [comment]
I'll resolve the merge conflict and ping when it's ready for merge.

**Comment by konklone** [comment]
Merge conflicts fixed.

**Comment by h-m-f-t** [comment]
👀 appreciate the assist! 😄

**Pull request merged**
