### PR TITLE
Update for sslyze changes

### PR DESCRIPTION
**Pull request by jsf9k**
sslyze has had some breaking changed in recent updates.  This PR modifies the pshtt code to handle this.

Thanks to @echudow for pointing out these changes to me.

### CODE REVIEW

**Review by dav3r — APPROVED** [review]
LGTM ⚙️

**Review by IanLee1521 — APPROVED** [review]
Looks good!

**Comment by echudow** [comment]
@jsf9k If you also use the `sslyze` scanner in `domain-scan`, remember to update that one too.

**Comment by echudow** [comment]
@jsf9k Also, since now `sslyze` does the certificate verification differently, we've found that some sites that don't support "modern" encryption (e.g., TLS 1.2) automatically fail the certificate verification checks since `sslyze` doesn't support the certificate verification for them anymore even though they use valid trusted certificates, so that might negatively affect some results.  See https://github.com/nabla-c0d3/sslyze/blob/763832e0abc782ee1164d4c619398ec4459f886c/sslyze/plugins/certificate_info_plugin.py#L241-L250 and https://github.com/nabla-c0d3/sslyze/blob/763832e0abc782ee1164d4c619398ec4459f886c/sslyze/plugins/certificate_info_plugin.py#L80-L82.

**Comment by jsf9k** [comment]
I reverted this PR because it was not ready to be merged yet.  I haven't tested yet.  I should have created a draft PR.  My apologies.

**Comment by jsf9k** [comment]
> @jsf9k If you also use the `sslyze` scanner in `domain-scan`, remember to update that one too.

@echudow Yes, that is 18F/domain-scan#310.

**Comment by jsf9k** [comment]
> @jsf9k Also, since now `sslyze` does the certificate verification differently, we've found that some sites that don't support "modern" encryption (e.g., TLS 1.2) automatically fail the certificate verification checks since `sslyze` doesn't support the certificate verification for them anymore even though they use valid trusted certificates, so that might negatively affect some results. See https://github.com/nabla-c0d3/sslyze/blob/763832e0abc782ee1164d4c619398ec4459f886c/sslyze/plugins/certificate_info_plugin.py#L241-L250 and https://github.com/nabla-c0d3/sslyze/blob/763832e0abc782ee1164d4c619398ec4459f886c/sslyze/plugins/certificate_info_plugin.py#L80-L82.

Ugh.  Thanks for pointing out that landmine before I stepped on it, @echudow.

**Pull request merged**
